version: '3.7'
services:
  pygrok:
    container_name: pygrok
    image: defelo/pygrok
    build: .
    restart: always
    tty: true
    environment:
      NGROK_TOKEN: 'REPLACE'
      REGION: 'eu'
      TOTP_SECRET: 'REPLACE'
      TELEGRAM_BOT_TOKEN: 'REPLACE'
      TELEGRAM_BOT_OWNER: 'REPLACE'
      ARCH: 'x86'
      PROTOCOL: 'tcp'  # example config for ssh
      PORT: 22
#      DESTINATION: 'other-container'
      HOSTNAME: 'my device'
